from typing import List, Dict, Tuple, Callable, Optional

from BaseClasses import CollectionState


class RegionData:
    name: str
    exits: List[Dict[str, Optional[Callable[[CollectionState, int], bool]]]]
    locations: List[Tuple[str,
                          Optional[Callable[[CollectionState, int], bool]]]]

    def __init__(
        self,
        name: str, exits: List[Tuple[str, Optional[Callable[[CollectionState, int], bool]]]],
        locations: List[Tuple[str,
                              Optional[Callable[[CollectionState, int], bool]]]]
    ):
        self.name = name
        self.exits = exits
        self.locations = locations


def has_flight(state: CollectionState, player: int):
    return state.has("Progressive Booster", player) or state.has_all({"Machine Gun", "Level MG"})


def can_break_blocks(state: CollectionState, player: int):
    return state.has_any({"Blade", "Machine Gun", "Nemesis", "Progressive Polar Star"}, player)


def can_kill_bosses(state: CollectionState, player: int):
    return state.has_any({"Blade", "Bubbler", "Fireball", "Machine Gun", "Nemesis", "Progressive Polar Star", "Snake"}, player)


def has_weapon(state: CollectionState, player: int):
    return state.has_any({"Blade", "Bubbler", "Fireball", "Machine Gun", "Nemesis", "Progressive Missile Launcher", "Progressive Polar Star", "Snake"}, player)


def remove_points_of_no_return(state: CollectionState, player: int):
    return True


def reset_iframes(state: CollectionState, player: int):
    return True  # state.has("Map System", player)


def traverse_labyrinth_w(state: CollectionState, player: int):
    return False


# Autogenerated region list goes here
REGIONS: List[RegionData] = [
    RegionData(
        "Egg Corridor - Door to Cthulhu's Abode (Lower)",
        [
            ("Outside Cthulhu's Abode", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - Door to Cthulhu's Abode (Upper)",
        [
            ("Outside Cthulhu's Abode", lambda state, player: True),
            ("Pickup (Cthulhu's Abode)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - Teleporter to Arthur's House",
        [
            ("Hint - Blue Robot", lambda state, player: True),
            ("Pickup (Basil Spot)", lambda state, player: True),
            ("Outside Cthulhu's Abode", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1"))),
            ("Event - Level MG", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - Outside Cthulhu's Abode",
        [
            ("Door to Cthulhu's Abode (Lower)", lambda state, player: True),
            ("Door to Cthulhu's Abode (Upper)", lambda state, player: has_flight(state, player) or (state.has("tricks;Dboost;1") and state.has("damage;Damage;2"))),
            ("Teleporter to Arthur's House", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1"))),
            ("Outside Egg Observation Room", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - Outside Egg Observation Room",
        [
            ("Outside Cthulhu's Abode", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1"))),
            ("H/V Trigger to Egg No. 06", lambda state, player: True),
            ("Door to Egg Observation Room", lambda state, player: True),
            ("H/V Trigger to Egg No. 01", lambda state, player: True),
            ("Outside Egg No. 00", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - H/V Trigger to Egg No. 06",
        [
            ("Outside Egg Observation Room", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - Door to Egg Observation Room",
        [
            ("Outside Egg Observation Room", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - H/V Trigger to Egg No. 01",
        [
            ("Outside Egg Observation Room", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - Outside Egg No. 00",
        [
            ("Outside Egg Observation Room", lambda state, player: True),
            ("Event - Igor", lambda state, player: can_kill_bosses(state, player) or (state.has("items;supers;1") and state.has("tricks;BossMissiles;1") and state.has("items;missile;8")) or (state.has("items;missiles;1") and state.has("items;missile;18") and state.has("tricks;BossMissiles;2"))),
            ("Door to Egg No. 00", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - Door to Egg No. 00",
        [
            ("Event - Igor", lambda state, player: True),
            ("Outside Egg No. 00", lambda state, player: True),
            ("Door to Side Room", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor - Door to Side Room",
        [
            ("Door to Egg No. 00", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Cthulhu's Abode - Door to Egg Corridor (Lower)",
        [
            ("Door to Egg Corridor (Upper)", lambda state, player: True),
            ("Hint - Cthulhu", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Cthulhu's Abode - Door to Egg Corridor (Upper)",
        [
            ("Door to Egg Corridor (Lower)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Cthulhu's Abode - Save Point",
        [
            ("Door to Egg Corridor (Lower)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg No. 06 - Door to Egg Corridor",
        [
            ("Pickup (Egg Chest)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Observation Room - Door to Egg Corridor",
        [
            ("Pickup (Egg Observation Room Chest)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg No. 01 - Door to Egg Corridor",
        [
            ("Event - Lowered Egg Corridor Barrier", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg No. 00 - Door to Egg Corridor",
        [
            ("Event - Saved Sue", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Side Room - Door to Egg Corridor",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Side Room - Save Point",
        [
            ("Door to Egg Corridor", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Side Room - Refill",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Door to Santa's House",
        [
            ("West Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Door to Chaco's House",
        [
            ("West Side", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1") and has_flight(state, player)) or state.has("tricks;pacifist;2"))
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Entrance from Chaco's House",
        [
            ("Event - Entered Grasstown from Chaco Fireplace", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Door to Power Room",
        [
            ("East Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Door to Save Point",
        [
            ("East Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Door to Grasstown Hut",
        [
            ("East Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Door to Shelter",
        [
            ("East Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Door to Execution Chamber",
        [
            ("East Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Door to Gum",
        [
            ("East Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - West Side",
        [
            ("Door to Santa's House", lambda state, player: True),
            ("Pickup (West Grasstown Floor)", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1"))),
            ("Pickup (West Grasstown Ceiling)", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1"))),
            ("Door to Chaco's House", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1") and has_flight(state, player)) or state.has("tricks;pacifist;2")),
            ("Area Centre", lambda state, player: has_flight(state, player) or state.has("events;eventFans;1") or (state.has("tricks;IframeReset;1") and ((state.has("tricks;Dboost;1") and state.has("damage;Damage;6")) or (state.has("tricks;Dboost;2") and state.has("damage;Damage;4")) or (state.has("tricks;Dboost;3") and state.has("damage;Damage;2") and has_weapon(state, player))) and reset_iframes(state, player) and (has_weapon(state, player) or (state.has("tricks;pacifist;1") and state.has("damage;Damage;5")) or state.has("tricks;pacifist;2")))),
            ("Teleporter to Arthur's House", lambda state, player: True),
            ("Pickup (Kulala)", lambda state, player: has_weapon(state, player) and state.has("events;eventJellies;1")),
            ("Event - Return Santa's Key", lambda state, player: True),
            ("Hint - Cthulhu (West)", lambda state, player: True),
            ("Event - Level MG (West)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - East Side",
        [
            ("Door to Power Room", lambda state, player: True),
            ("Door to Save Point", lambda state, player: True),
            ("Door to Grasstown Hut", lambda state, player: has_flight(state, player) or state.has("events;eventFans;1") or (state.has("tricks;Dboost;2") and state.has("tricks;IframeReset;1") and state.has("damage;Damage;4") and reset_iframes(state, player))),
            ("Door to Shelter", lambda state, player: True),
            ("Door to Execution Chamber", lambda state, player: True),
            ("Door to Gum", lambda state, player: state.has("items;gumKey;1") and (has_flight(state, player) or state.has("events;eventFans;1"))),
            ("Pickup (Grasstown East Chest)", lambda state, player: True),
            ("Pickup (Kazuma Crack)", lambda state, player: True),
            ("Pickup (Kazuma Chest)", lambda state, player: True),
            ("Area Centre", lambda state, player: (state.has("events;eventFans;1") or has_flight(state, player) or (remove_points_of_no_return(state, player) and state.has("events;eventFireplace;1")) or ((state.has("tricks;GravHop;5")) or (state.has("tricks;Dboost;3") and state.has("damage;Damage;2")) or (state.has("tricks;Dboost;2") and state.has("damage;Damage;3")))) and (has_weapon(state, player) or (state.has("tricks;pacifist;2") and ((state.has("tricks;Dboost;1") and state.has("damage;Damage;3")) or has_flight(state, player))) or (state.has("tricks;pacifist;3") and state.has("tricks;GravHop;3")))),
            ("Event - Saved Kazuma", lambda state, player: True),
            ("Hint - Cthulhu (East)", lambda state, player: True),
            ("Event - Level MG (East)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Area Centre",
        [
            ("West Side", lambda state, player: True),
            ("East Side", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;2") and (has_flight(state, player) or (state.has("damage;Damage;3") and state.has("tricks;Dboost;1")))) or (state.has("tricks;pacifist;3") and state.has("tricks;GravHop;3")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown - Teleporter to Arthur's House",
        [
            ("West Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Santa's House - Door to Grasstown",
        [
            ("Pickup (Santa)", lambda state, player: True),
            ("Pickup (Santa's Fireplace)", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Santa's House - Save Point",
        [
            ("Door to Grasstown", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Santa's House - Refill",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Chaco's House - Door to Grasstown",
        [
            ("Exit to Grasstown", lambda state, player: True),
            ("Event - Summon Jellies", lambda state, player: True),
            ("Pickup (Chaco's Bed, where you two Had A Nap)", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Chaco's House - Exit to Grasstown",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Chaco's House - Save Point",
        [
            ("Door to Grasstown", lambda state, player: True),
            ("Bed", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Chaco's House - Bed",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Power Room - Door to Grasstown",
        [
            ("Event - Activated Fans", lambda state, player: True),
            ("Pickup (MALCO)", lambda state, player: state.has("events;eventFans;1") and state.has("items;charcoal;1") and state.has("items;Juice;1") and state.has("items;gumBase;1") and state.has("events;eventBalrog2;1")),
            ("Hint - MALCO", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Save Point - Door to Grasstown",
        [
            ("Save Point", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Save Point - Save Point",
        [
            ("Door to Grasstown", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Save Point - Refill",
        [
            ("Door to Grasstown", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Grasstown Hut - Door to Grasstown",
        [
            ("Pickup (Grasstown Hut)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Execution Chamber - Door to Grasstown",
        [
            ("Pickup (Execution Chamber)", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNMissiles;1") and state.has("items;missiles;1") and state.has("items;missile;2")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Gum - Door to Grasstown",
        [
            ("Pickup (Gum Chest)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Shelter - Door to Grasstown",
        [
            ("Save Point", lambda state, player: True),
            ("Teleporter to Jail No. 2", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Shelter - Save Point",
        [
            ("Door to Grasstown", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Shelter - Teleporter to Jail No. 2",
        [
            ("Door to Grasstown", lambda state, player: True),
            ("Event - Saved Kazuma", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Shelter - Refill",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth B - Door to Boulder Chamber",
        [
            ("Door to Labyrinth W", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth B - Door to Labyrinth W",
        [
            ("Door to Boulder Chamber", lambda state, player: True),
            ("Teleporter to Arthur's House", lambda state, player: True),
            ("Event - Enter Labyrinth B from Above", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth B - Teleporter to Arthur's House",
        [
            ("Door to Labyrinth W", lambda state, player: has_flight(state, player) or (state.has("events;eventMazeB;1") and remove_points_of_no_return(state, player))),
            ("Pickup (Booster Chest)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth B - Save Point",
        [
            ("Door to Labyrinth W", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth B - Refill",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Boulder Chamber - Door to Labyrinth B",
        [
            ("Event - Balrog 3", lambda state, player: state.has("events;eventCureAll;1") and (can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;2") and (state.has("items;missiles;24") or (state.has("items;missiles;15") and state.has("items;supers;1")))))),
            ("Pickup (Boulder Chest)", lambda state, player: True),
            ("Door to Labyrinth M", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Boulder Chamber - Door to Labyrinth M",
        [
            ("Door to Labyrinth B", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Boulder Chamber - Save Point",
        [
            ("Door to Labyrinth B", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth M - Door to Boulder Chamber",
        [
            ("Door to Dark Place", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;3") and has_flight(state, player)) or state.has("tricks;pacifist;4"))
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth M - Door to Dark Place",
        [
            ("Door to Boulder Chamber", lambda state, player: state.has("events;eventBalrog3;1") and (has_weapon(state, player) or (state.has("tricks;pacifist;3") and has_flight(state, player)) or state.has("tricks;SNBubbler;4"))),
            ("Teleporter to Labyrinth Shop", lambda state, player: has_weapon(state, player) or state.has("tricks;pacifist;1"))
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth M - Teleporter to Labyrinth Shop",
        [
            ("Door to Dark Place", lambda state, player: has_weapon(state, player) or state.has("tricks;pacifist;1")),
            ("Event - Level MG", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Dark Place - Door to Labyrinth M",
        [
            ("Door to Core", lambda state, player: True),
            ("Exit to Waterway", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Dark Place - Door to Core",
        [
            ("Door to Labyrinth M", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Dark Place - Exit to Waterway",
        [
            ("Door to Labyrinth M", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Dark Place - Entrance from Reservoir",
        [
            ("Door to Labyrinth M", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Dark Place - Save Point",
        [
            ("Door to Labyrinth M", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Core - Door to Dark Place",
        [
            ("Inner Room", lambda state, player: state.has("events;eventBalrog3;1") and (can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;1") and (state.has("items;missiles;1") or state.has("items;supers;1")) and state.has("items;missile;2"))))
        ],
        [
            
        ]
    ),
    RegionData(
        "Core - Inner Room",
        [
            ("Door to Dark Place", lambda state, player: True),
            ("Event - Core", lambda state, player: can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;4") and state.has("items;missiles;1") and state.has("items;missile;38")) or (state.has("tricks;BossMissiles;3") and state.has("items;supers;1") and state.has("items;missile;16")) or (state.has("tricks;pacifist;2"))),
            ("Pickup (Robot's Arm)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Waterway - Entrance from Dark Place",
        [
            ("Door to Waterway Cabin", lambda state, player: state.has("items;airTank;1") and (has_weapon(state, player) or state.has("tricks;pacifist;2")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Waterway - Exit to Main Artery",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Waterway - Door to Waterway Cabin",
        [
            ("Exit to Main Artery", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Waterway Cabin - Door to Waterway",
        [
            ("Event - Drained Curly", lambda state, player: True),
            ("Bed", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Waterway Cabin - Save Point",
        [
            ("Door to Waterway", lambda state, player: True),
            ("Bed", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Waterway Cabin - Bed",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Main Artery - Entrance from Waterway",
        [
            ("Exit to Reservoir", lambda state, player: True),
            ("Event - Ironhead", lambda state, player: can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;2") and state.has("items;supers;1") and state.has("items;missile;10")) or (state.has("tricks;BossMissiles;3") and state.has("items;missiles;1") and state.has("items;missile;24")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Main Artery - Exit to Reservoir",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth I - Door to Labyrinth H",
        [
            ("Room Bottom", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth I - Room Bottom",
        [
            ("Door to Labyrinth H", lambda state, player: True),
            ("Event - Opened Labyrinth I Door", lambda state, player: has_weapon(state, player) or ((state.has("tricks;pacifist;1") and has_flight(state, player))) or state.has("tricks;pacifist;3")),
            ("Pickup (Labyrinth Life Capsule)", lambda state, player: has_weapon(state, player) or state.has("tricks;pacifist;3") or (state.has("tricks;pacifist;2") and has_flight(state, player))),
            ("Save Point", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;1") and state.has("items;missiles;1") and state.has("items;supers;1") and state.has("items;missile;1")) or state.has("tricks;GravHop;3")),
            ("Hint - Blue Robot (Left)", lambda state, player: True),
            ("Hint - Blue Robot (Right)", lambda state, player: True),
            ("Event - Use Labyrinth I Teleporter", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth I - Entrance from Sand Zone Storehouse",
        [
            ("Room Bottom", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth I - Teleporter to Sand Zone",
        [
            ("Room Bottom", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth I - Save Point",
        [
            ("Room Bottom", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth H - Door to Labyrinth I",
        [
            ("Door to Labyrinth W", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth H - Door to Labyrinth W",
        [
            ("Door to Labyrinth I", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth W - Door to Labyrinth H",
        [
            ("Outside Camp", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth W - Door to Labyrinth Shop",
        [
            ("Outside Camp", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth W - Outside Camp",
        [
            ("Door to Labyrinth H", lambda state, player: True),
            ("Door to Labyrinth Shop", lambda state, player: True),
            ("Door to Camp (Lower)", lambda state, player: True),
            ("Door to Camp (Upper)", lambda state, player: can_break_blocks(state, player) and ((state.has("tricks;Dboost;1") and state.has("damage;Damage;8")) or has_flight(state, player) or (state.has("tricks;Dboost;2") and state.has("damage;Damage;3"))) and traverse_labyrinth_w(state, player)),
            ("Door to Clinic Ruins", lambda state, player: state.has("items;clinicKey;1") and traverse_labyrinth_w(state, player)),
            ("Event - Level MG", lambda state, player: True),
            ("Before Monster X", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth W - Door to Camp (Lower)",
        [
            ("Outside Camp", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth W - Door to Camp (Upper)",
        [
            ("Outside Camp", lambda state, player: can_break_blocks(state, player) and traverse_labyrinth_w(state, player))
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth W - Door to Clinic Ruins",
        [
            ("Outside Camp", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth W - Door to Labyrinth B",
        [
            ("Before Monster X", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth W - Before Monster X",
        [
            ("Outside Camp", lambda state, player: True),
            ("Door to Labyrinth B", lambda state, player: True),
            ("Event - Monster X", lambda state, player: can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;3") and state.has("items;supers;1") and state.has("items;missile;30")) or (state.has("tricks;BossMissiles;4") and state.has("items;missiles;1") and state.has("items;missile;60")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth Shop - Door to Labyrinth W",
        [
            ("Pickup (Chaba Chest (Machine Gun))", lambda state, player: True),
            ("Pickup (Chaba Chest (Fireball))", lambda state, player: True),
            ("Pickup (Chaba Chest (Spur))", lambda state, player: True),
            ("Teleporter to Labyrinth M", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth Shop - Teleporter to Labyrinth M",
        [
            ("Door to Labyrinth W", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Labyrinth Shop - Save Point",
        [
            ("Door to Labyrinth W", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Camp - Door to Labyrinth W (Lower)",
        [
            ("Door to Labyrinth W (Upper)", lambda state, player: True),
            ("Pickup (Dr. Gero)", lambda state, player: True),
            ("Event - Cure-All", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Camp - Door to Labyrinth W (Upper)",
        [
            ("Door to Labyrinth W (Lower)", lambda state, player: True),
            ("Pickup (Camp Chest)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Camp - Room Spawn",
        [
            ("Door to Labyrinth W (Lower)", lambda state, player: True),
            ("Event - Camp", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Camp - Save Point",
        [
            ("Door to Labyrinth W (Lower)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Clinic Ruins - Door to Labyrinth W",
        [
            ("Pickup (Puu Black Boss)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Final Cave - Door to Plantation",
        [
            ("Door to Balcony (Pre-Bosses)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Final Cave - Door to Balcony (Pre-Bosses)",
        [
            ("Door to Plantation", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Last Cave (Hidden) - Door to Plantation",
        [
            ("Before Red Demon", lambda state, player: state.has("items;booster2;1") and has_weapon(state, player))
        ],
        [
            
        ]
    ),
    RegionData(
        "Last Cave (Hidden) - Door to Balcony (Pre-Bosses)",
        [
            ("Before Red Demon", lambda state, player: state.has("items;booster2;1") and has_weapon(state, player))
        ],
        [
            
        ]
    ),
    RegionData(
        "Last Cave (Hidden) - Before Red Demon",
        [
            ("Door to Plantation", lambda state, player: True),
            ("Event - Red Demon", lambda state, player: can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;2") and state.has("items;supers;1") and state.has("items;missile;8")) or (state.has("tricks;BossMissiles;3") and state.has("items;missiles;1") and state.has("items;missile;18"))),
            ("Door to Balcony (Pre-Bosses)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Balcony (Pre-Bosses) - Exit to Throne Room",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Balcony (Pre-Bosses) - Door to Final Cave",
        [
            ("Door to Prefab Building", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Balcony (Pre-Bosses) - Door to Last Cave (Hidden)",
        [
            ("Door to Prefab Building", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Balcony (Pre-Bosses) - Door to Prefab Building",
        [
            ("Exit to Throne Room", lambda state, player: True),
            ("Door to Final Cave", lambda state, player: True),
            ("Door to Last Cave (Hidden)", lambda state, player: True),
            ("Event - Lowered Barrier", lambda state, player: (state.has("events;eventSue;1") and (state.has("misc;normalEnd;1") or (state.has("items;ironBond;1") and state.has("items;booster2;1") and (state.has("misc;bestEnd;1") or (state.has("events;eventBalfrog;1") and state.has("events;eventBalrog;1") and state.has("events;eventBalrog2;1") and state.has("events;eventBalrog3;1") and state.has("events;eventFightCurly;1") and state.has("events;eventIgor;1") and state.has("events;eventIronhead;1") and state.has("events;eventMaPignon;1") and state.has("events;eventMonsterX;1") and state.has("events;eventOmega;1") and state.has("events;eventPuu;1") and state.has("events;eventSisters;1") and state.has("events;eventToroko;1") and state.has("events;eventCore;1") and (state.has("misc;allBosses;1") or (state.has("misc;hundo;1") and ()))))))))
        ],
        [
            
        ]
    ),
    RegionData(
        "Prefab Building - Door to Balcony (Pre-Bosses)",
        [
            ("Save Point/Bed", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Prefab Building - Save Point/Bed",
        [
            ("Door to Balcony (Pre-Bosses)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Throne Room - Entrance from Balcony (Pre-Bosses)",
        [
            ("Event - Misery", lambda state, player: can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;3") and state.has("items;supers;1") and state.has("items;missile;13")) or (state.has("tricks;BossMissiles;4") and state.has("items;missiles;1") and state.has("items;missile;31")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Throne Room - Exit to Balcony (Post-Bosses)",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Throne Room - H/V Trigger to The King's Table",
        [
            ("Exit to Balcony (Post-Bosses)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "The King's Table - H/V Trigger to Throne Room",
        [
            ("Event - Doctor", lambda state, player: can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;2") and state.has("items;missiles;1") and state.has("items;missile;36")) or (state.has("tricks;BossMissiles;3") and state.has("items;supers;1") and state.has("items;missile;16")))
        ],
        [
            
        ]
    ),
    RegionData(
        "The King's Table - H/V Trigger to Black Space",
        [
            ("H/V Trigger to Throne Room", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Black Space - H/V Trigger to The King's Table",
        [
            ("Event - Undead Core", lambda state, player: can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;3") and state.has("items;supers;1") and state.has("items;missile;18")) or (state.has("tricks;BossMissiles;4") and state.has("items;missiles;1") and state.has("items;missile;42")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Balcony (Post-Bosses) - Entrance from Throne Room",
        [
            ("Event - Normal Ending", lambda state, player: state.has("misc;normalEnd;1") and state.has("events;eventCore2;1")),
            ("Exit to Prefab House", lambda state, player: state.has("items;ironBond;1") and (state.has("misc;bestEnd;1") or state.has("misc;allBosses;1") or state.has("misc;hundo;1") or state.has("misc;entranceRando;1")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Balcony (Post-Bosses) - Exit to Prefab House",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Balcony (Post-Bosses) - Entrance from Prefab House",
        [
            ("Entrance from Throne Room", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Prefab House - Entrance from Balcony (Post-Bosses)",
        [
            ("Exit to Balcony (Post-Bosses)", lambda state, player: True),
            ("Exit to Sacred Grounds - B1", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Prefab House - Exit to Balcony (Post-Bosses)",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Prefab House - Exit to Sacred Grounds - B1",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Prefab House - Save Point",
        [
            ("Entrance from Balcony (Post-Bosses)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sacred Grounds - B1 - Entrance from Prefab House",
        [
            ("Pickup (Hell B1 Spot)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sacred Grounds - B1 - Door to Sacred Grounds - B2",
        [
            ("Pickup (Hell B1 Spot)", lambda state, player: True),
            ("Event - Curly", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sacred Grounds - B2 - Door to Sacred Grounds - B1",
        [
            ("H/V Trigger to Sacred Grounds - B3", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sacred Grounds - B2 - H/V Trigger to Sacred Grounds - B3",
        [
            ("Door to Sacred Grounds - B1", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sacred Grounds - B3 - H/V Trigger to Sacred Grounds - B2",
        [
            ("Pickup (Hell B3 Chest)", lambda state, player: (has_flight(state, player) or (state.has("tricks;Dboost;1") and state.has("damage;Damage;10"))) and has_weapon(state, player)),
            ("Event - Heavy Press", lambda state, player: can_kill_bosses(state, player) and (has_flight(state, player) or (state.has("tricks;Dboost;1") and state.has("damage;Damage;10"))))
        ],
        [
            
        ]
    ),
    RegionData(
        "Sacred Grounds - B3 - Exit to Passage?",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Corridor - Door to Passage?",
        [
            ("Exit to Seal Chamber", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Corridor - Exit to Seal Chamber",
        [
            ("Door to Passage?", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Seal Chamber - Entrance from Corridor",
        [
            ("Event - Best Ending", lambda state, player: (can_kill_bosses(state, player) or (state.has("tricks;pacifist;1") and state.has("events;eventCurly3;1"))) and has_flight(state, player) and (state.has("misc;bestEnd;1") or state.has("misc;allBosses;1") or state.has("misc;hundo;1")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Start Point - Door to First Cave",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Start Point - Save Point",
        [
            ("Door to First Cave", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Start Point - Room Spawn",
        [
            ("Event - Start Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Start Point - Refill",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "First Cave - Door to Start Point",
        [
            ("Door to Hermit Gunsmith", lambda state, player: True),
            ("Door to Mimiga Village", lambda state, player: can_break_blocks(state, player) and (has_weapon(state, player) or state.has("events;startPoint;1"))),
            ("Pickup (First Cave Life Capsule)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "First Cave - Door to Hermit Gunsmith",
        [
            ("Door to Start Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "First Cave - Door to Mimiga Village",
        [
            ("Door to Start Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Hermit Gunsmith - Door to First Cave",
        [
            ("Pickup (Hermit Gunsmith Chest)", lambda state, player: True),
            ("Pickup (Tetsuzou)", lambda state, player: (state.has("items;polarStar;1") or state.has("items;spur;1")) and state.has("events;eventCore;1"))
        ],
        [
            
        ]
    ),
    RegionData(
        "Mimiga Village - Door to First Cave",
        [
            ("Room Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Mimiga Village - Room Centre",
        [
            ("Door to First Cave", lambda state, player: True),
            ("Door to Save Point", lambda state, player: True),
            ("Door to Reservoir", lambda state, player: True),
            ("Door to Yamashita Farm", lambda state, player: True),
            ("Door to Assembly Hall", lambda state, player: True),
            ("Door to Graveyard", lambda state, player: True),
            ("Door to Shack", lambda state, player: True),
            ("Door to Arthur's House", lambda state, player: True),
            ("Pickup (Mimiga Village Chest)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Mimiga Village - Door to Save Point",
        [
            ("Room Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Mimiga Village - Door to Reservoir",
        [
            ("Room Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Mimiga Village - Door to Yamashita Farm",
        [
            ("Room Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Mimiga Village - Door to Assembly Hall",
        [
            ("Room Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Mimiga Village - Door to Graveyard",
        [
            ("Room Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Mimiga Village - Door to Shack",
        [
            ("Room Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Mimiga Village - Door to Arthur's House",
        [
            ("Room Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Save Point - Door to Mimiga Village",
        [
            ("Save Point", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Save Point - Save Point",
        [
            ("Door to Mimiga Village", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Save Point - Refill",
        [
            ("Door to Mimiga Village", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Yamashita Farm - Door to Mimiga Village",
        [
            ("Pickup (Yamashita Farm)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Reservoir - Door to Mimiga Village",
        [
            ("Debug Cat to Dark Place", lambda state, player: state.has("misc;entranceRando;1") and state.has("events;eventIronhead;1")),
            ("Pickup (Reservoir)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Reservoir - Debug Cat to Dark Place",
        [
            ("Door to Mimiga Village", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Reservoir - Entrance from Main Artery",
        [
            ("Door to Mimiga Village", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Assembly Hall - Door to Mimiga Village",
        [
            ("Pickup (Assembly Hall Fireplace)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Graveyard - Door to Mimiga Village",
        [
            ("Door to Storage", lambda state, player: True),
            ("Pickup (Arthur's Grave)", lambda state, player: True),
            ("Pickup (Mr. Little (Graveyard))", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Graveyard - Door to Storage",
        [
            ("Door to Mimiga Village", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Storage - Door to Graveyard",
        [
            ("Pickup (Storage? Chest)", lambda state, player: True),
            ("Event - Ma Pignon", lambda state, player: state.has("items;mushBadge;1") and (state.has("items;polarStar;1") or state.has("items;machineGun;1") or state.has("items;bubbler;1") or state.has("items;fireball;1") or state.has("items;spur;1") or state.has("items;snake;1") or state.has("items;nemesis;1")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Shack - Door to Mimiga Village",
        [
            ("Event - Toroko Kidnapped", lambda state, player: state.has("items;locket;1") and has_weapon(state, player)),
            ("Event - Balrog 1", lambda state, player: state.has("events;eventToroko2;1") and (can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;1") and ((state.has("items;missiles;1") and state.has("items;missile;4")) or (state.has("items;supers;2") and state.has("items;missile;2")))))),
            ("Event - Level MG", lambda state, player: state.has("items;machineGun;1") and state.has("events;eventBalrog;1"))
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Door to Mimiga Village",
        [
            ("Main Teleporter", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Main Teleporter",
        [
            ("Door to Mimiga Village", lambda state, player: True),
            ("Pickup (Professor Booster)", lambda state, player: True),
            ("Save Point", lambda state, player: True),
            ("Teleporter to Egg Corridor", lambda state, player: True),
            ("Teleporter to Grasstown", lambda state, player: True),
            ("Teleporter to Sand Zone", lambda state, player: True),
            ("Teleporter to Labyrinth B", lambda state, player: True),
            ("Teleporter to Teleporter", lambda state, player: True),
            ("Teleporter to Egg Corridor?", lambda state, player: state.has("events;eventCore;1") or state.has("events;eventEgg2Teleport;1")),
            ("Room Spawn", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Save Point",
        [
            ("Main Teleporter", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Teleporter to Egg Corridor",
        [
            ("Main Teleporter", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Teleporter to Grasstown",
        [
            ("Main Teleporter", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Teleporter to Sand Zone",
        [
            ("Main Teleporter", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Teleporter to Labyrinth B",
        [
            ("Main Teleporter", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Teleporter to Teleporter",
        [
            ("Main Teleporter", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Teleporter to Egg Corridor?",
        [
            ("Main Teleporter", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Room Spawn",
        [
            ("Event - Arthur's House", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Arthur's House - Refill",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Rest Area",
        [
            ("Middle Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Teleporter",
        [
            ("Lower Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Storehouse",
        [
            ("Middle Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Jail No. 1 (Lower)",
        [
            ("Upper Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Jail No. 1 (Upper)",
        [
            ("Upper Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Jail No. 2",
        [
            ("Upper Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Last Cave (Hidden)",
        [
            ("Top Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Passage?",
        [
            ("Middle Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Hideout",
        [
            ("Middle Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Lower Level",
        [
            ("Door to Teleporter", lambda state, player: True),
            ("Middle Level", lambda state, player: True),
            ("Pickup (Kanpachi's Bucket)", lambda state, player: True),
            ("Pickup (Jammed it into Curly's mouth)", lambda state, player: state.has("events;eventCurly;1") and state.has("items;maPignon;1")),
            ("Hint - Cthulhu", lambda state, player: True),
            ("Event - Level MG", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Middle Level",
        [
            ("Door to Rest Area", lambda state, player: True),
            ("Door to Storehouse", lambda state, player: True),
            ("Door to Passage?", lambda state, player: True),
            ("Door to Hideout", lambda state, player: True),
            ("Lower Level", lambda state, player: True),
            ("Pickup (Broken Sprinker)", lambda state, player: True),
            ("Upper Level", lambda state, player: True),
            ("Top Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Upper Level",
        [
            ("Door to Jail No. 1 (Lower)", lambda state, player: True),
            ("Door to Jail No. 1 (Upper)", lambda state, player: True),
            ("Door to Jail No. 2", lambda state, player: True),
            ("Middle Level", lambda state, player: True),
            ("Pickup (Plantation Platforming Spot)", lambda state, player: has_flight(state, player) or (state.has("tricks;Dboost;3") and state.has("tricks;IframeReset;1") and state.has("damage;Damage;10") and reset_iframes(state, player))),
            ("Pickup (Plantation Puppy)", lambda state, player: state.has("events;eventRocket;1")),
            ("Top Level", lambda state, player: (state.has("items;booster2;1") and state.has("items;machineGun;1") and state.has("tricks;Dboost;4") and state.has("damage;Damage;2")) or (state.has("items;booster2;1") and state.has("tricks;Dboost;5")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Door to Final Cave",
        [
            ("Top Level", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Plantation - Top Level",
        [
            ("Door to Last Cave (Hidden)", lambda state, player: state.has("items;booster2;1") and (state.has("events;eventRocket;1"))),
            ("Upper Level", lambda state, player: True),
            ("Door to Final Cave", lambda state, player: state.has("items;booster2;1") and (state.has("events;eventRocket;1")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Storehouse - Door to Plantation",
        [
            ("Door to Outer Wall", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Storehouse - Door to Outer Wall",
        [
            ("Door to Plantation", lambda state, player: True),
            ("Pickup (Itoh)", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Storehouse - Save Point",
        [
            ("Door to Outer Wall", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Passage? - Door to Plantation",
        [
            ("Door to Statue Chamber", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Passage? - Door to Statue Chamber",
        [
            ("Door to Plantation", lambda state, player: True),
            ("Door to Corridor", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Passage? - Door to Corridor",
        [
            ("Door to Statue Chamber", lambda state, player: has_flight(state, player) and state.has("events;eventHell4;1"))
        ],
        [
            
        ]
    ),
    RegionData(
        "Passage? - Entrance from Sacred Grounds - B3",
        [
            ("Event - Entered Passage from Above", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Statue Chamber - Door to Passage?",
        [
            ("Hint - Numahachi 1", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Rest Area - Door to Plantation",
        [
            ("Pickup (Megane)", lambda state, player: state.has("items;mask;1") and state.has("items;brokenSprinkler;1")),
            ("Bed", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Rest Area - Bed",
        [
            ("Door to Plantation", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Teleporter - Door to Plantation",
        [
            ("Room Hub", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Teleporter - Room Hub",
        [
            ("Door to Plantation", lambda state, player: True),
            ("Event - Droll Attack", lambda state, player: True),
            ("Teleporter to Arthur's House", lambda state, player: state.has("items;teleportKey;1") or state.has("events;eventDroll;1")),
            ("Exit to Jail No. 1", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Teleporter - Teleporter to Arthur's House",
        [
            ("Room Hub", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Teleporter - Exit to Jail No. 1",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Jail No. 1 - Door to Plantation (Upper)",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Jail No. 1 - Entrance from Teleporter",
        [
            ("Door to Plantation (Upper)", lambda state, player: True),
            ("Pickup (Jail No. 1)", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Jail No. 1 - Door to Plantation (Lower)",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Jail No. 1 - Save Point",
        [
            ("Entrance from Teleporter", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Jail No. 2 - Door to Plantation",
        [
            ("Teleporter to Shelter", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;1") and state.has("items;missiles;1")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Jail No. 2 - Teleporter to Shelter",
        [
            ("Door to Plantation", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;1") and state.has("items;missiles;1")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Hideout - Door to Plantation",
        [
            ("Pickup (Chivalry Sakamoto's Wife)", lambda state, player: True),
            ("Event - Built Rocket", lambda state, player: (state.has("items;booster1;1") or state.has("items;booster2;1")) and state.has("items;newSprinkler;1") and state.has("items;controller;1")),
            ("Bed", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Hideout - Bed",
        [
            ("Door to Plantation", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Hideout - Save Point",
        [
            ("Bed", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - Door to Cthulhu's Abode? (Upper)",
        [
            ("Area Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - Door to Cthulhu's Abode? (Lower)",
        [
            ("West Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - West Side",
        [
            ("Door to Cthulhu's Abode? (Lower)", lambda state, player: True),
            ("Pickup (Dragon Chest)", lambda state, player: has_weapon(state, player) or state.has("tricks;pacifist;3") or (state.has("tricks;pacifist;2") and state.has("damage;Damage;10") and state.has("tricks;Dboost;1"))),
            ("Event - Used Egg Corridor? Teleporter", lambda state, player: True),
            ("Event - Level MG (West)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - Area Centre",
        [
            ("Door to Cthulhu's Abode? (Upper)", lambda state, player: True),
            ("Door to Egg Observation Room? (West)", lambda state, player: True),
            ("Event - Level MG (Centre)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - East Side",
        [
            ("Door to Egg Observation Room? (East)", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1") and has_flight(state, player)) or (state.has("tricks;Dboost;1") and state.has("damage;Damage;10") and state.has("tricks;pacifist;3"))),
            ("Door to Egg No. 00", lambda state, player: True),
            ("Door to Side Room", lambda state, player: True),
            ("Event - Level MG (East)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - Door to Egg Observation Room? (West)",
        [
            ("Area Centre", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - Door to Egg Observation Room? (East)",
        [
            ("East Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - Door to Egg No. 00",
        [
            ("East Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - Door to Side Room",
        [
            ("East Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Corridor? - Teleporter to Arthur's House",
        [
            ("West Side", lambda state, player: True),
            ("Hint - Blue Robot", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Cthulhu's Abode? - Door to Egg Corridor? (Upper)",
        [
            ("Door to Egg Corridor? (Lower)", lambda state, player: has_weapon(state, player) and (can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;1") and state.has("items;missiles;3"))))
        ],
        [
            
        ]
    ),
    RegionData(
        "Cthulhu's Abode? - Door to Egg Corridor? (Lower)",
        [
            ("Door to Egg Corridor? (Upper)", lambda state, player: has_weapon(state, player) and (can_break_blocks(state, player) or (state.has("tricks;SNMissiles;1") and state.has("items;missiles;3")) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1"))))
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Observation Room? - Door to Egg Corridor? (Western)",
        [
            ("Door to Egg Corridor? (Eastern)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Observation Room? - Door to Egg Corridor? (Eastern)",
        [
            ("Door to Egg Corridor? (Western)", lambda state, player: state.has("events;eventSisters;1") or has_flight(state, player)),
            ("Pickup (Sisters Boss)", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg Observation Room? - Save Point",
        [
            ("Door to Egg Corridor? (Eastern)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Side Room - Door to Egg Corridor?",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Side Room - Save Point",
        [
            ("Door to Egg Corridor?", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Side Room - Refill",
        [
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg No. 00 - Door to Egg Corridor?",
        [
            ("Door to Outer Wall", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Egg No. 00 - Door to Outer Wall",
        [
            ("Door to Egg Corridor?", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Outer Wall - Door to Egg No. 00",
        [
            ("Room Bottom", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Outer Wall - Door to Little House",
        [
            ("Room Bottom", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Outer Wall - Outside Clock Room",
        [
            ("Room Bottom", lambda state, player: True),
            ("Room Top", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;2") and has_flight(state, player)) or (state.has("tricks;pacifist;3") and state.has("damage;Damage;5")) or (state.has("tricks;pacifist;4"))),
            ("Door to Clock Room", lambda state, player: True),
            ("Event - Level MG", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Outer Wall - Door to Storehouse",
        [
            ("Event - Entered Outer Wall from Storehouse", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Outer Wall - Room Bottom",
        [
            ("Door to Egg No. 00", lambda state, player: True),
            ("Door to Little House", lambda state, player: True),
            ("Outside Clock Room", lambda state, player: has_flight(state, player) or (remove_points_of_no_return(state, player) and state.has("events;eventOside;1"))),
            ("Event - Bad Ending", lambda state, player: state.has("misc;badEnd;1") and state.has("events;eventKazuma;1") and state.has("events;eventCore;1"))
        ],
        [
            
        ]
    ),
    RegionData(
        "Outer Wall - Room Top",
        [
            ("Outside Clock Room", lambda state, player: True),
            ("Door to Storehouse", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Outer Wall - Door to Clock Room",
        [
            ("Event - Entered Outer Wall from Clock Room", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Little House - Door to Outer Wall",
        [
            ("Pickup (Little House)", lambda state, player: state.has("items;blade;1") and state.has("items;mrLittle;1")),
            ("Hint - Mrs. Little", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Clock Room - Door to Outer Wall",
        [
            ("Pickup (Clock Room)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Door to Jenka's House",
        [
            ("Outside Jenka's House", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Teleporter to Arthur's House",
        [
            ("Outside Sand Zone Residence", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;1") and state.has("items;missiles;1")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Outside Sand Zone Residence",
        [
            ("Teleporter to Arthur's House", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;1") and (state.has("items;missiles;1") or state.has("items;supers;1")) and state.has("items;missile;1"))),
            ("Door to Sand Zone Residence", lambda state, player: True),
            ("Above Sunstones", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNMissiles;2") and state.has("items;missiles;1") and state.has("items;missile;3")) or (state.has("tricks;SNMissiles;3") and (state.has("items;missile;3") or (state.has("items;missile;1") and state.has("items;supers;1")))) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Door to Sand Zone Residence",
        [
            ("Outside Sand Zone Residence", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Lower Side",
        [
            ("Door to Deserted House", lambda state, player: True),
            ("Pickup (Puppy (Run))", lambda state, player: True),
            ("Outside Jenka's House", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or ((state.has("tricks;SNMissiles;2") and state.has("items;missile;3")) or (state.has("tricks;SNMissiles;3") and state.has("items;missile;2")))),
            ("Outside Sand Zone Storehouse", lambda state, player: has_flight(state, player) or (has_flight(state, player) and state.has("tricks;pacifist;1")) or state.has("tricks;pacifist;2")),
            ("Event - Level MG (Lower)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Door to Deserted House",
        [
            ("Lower Side", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Exit to Sand Zone Storehouse",
        [
            
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Above Sunstones",
        [
            ("Outside Sand Zone Residence", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or ((state.has("tricks;SNMissiles;2") and state.has("items;missile;3")) or (state.has("tricks;SNMissiles;3") and state.has("items;missile;2")))),
            ("Pickup (Polish Spot)", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or ((state.has("items;missile;10") and state.has("tricks;SNMissiles;2")) or (state.has("tricks;SNMissiles;3") and state.has("items;missile;5")))),
            ("Before Omega", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or ((state.has("tricks;SNMissiles;2") and state.has("items;missile;27")) or (state.has("tricks;SNMissiles;3") and state.has("items;missile;13")) or (state.has("tricks;SNMissiles;4") and state.has("items;missile;1")))),
            ("Outside Jenka's House", lambda state, player: state.has("events;eventOmega;1") and (can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;2") and state.has("items;missile;4")) or (state.has("tricks;SNMissiles;3") and state.has("items;missile;2")) or (state.has("tricks;SNMissiles;4") and state.has("items;missile;1")))),
            ("Pawprint Spot", lambda state, player: state.has("events;eventOmega;1") and (can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;2") and state.has("items;missiles;3")))),
            ("Event - Level MG (Upper)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Before Omega",
        [
            ("Event - Omega", lambda state, player: (can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or ((state.has("tricks;SNMissiles;2") and state.has("items;missile;6")) or (state.has("tricks;SNMissiles;3") and state.has("items;missile;2")) or (state.has("tricks;SNMissiles;4") and state.has("items;missile;1")))) and (can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;1") and state.has("items;supers;1") and state.has("items;missile;11")) or (state.has("tricks;BossMissiles;2") and state.has("items;supers;1") and state.has("items;missile;10")) or (state.has("tricks;BossMissiles;3") and state.has("items;missiles;1") and state.has("items;missile;50")) or (state.has("tricks;BossMissiles;5") and state.has("items;missiles;1") and state.has("items;missile;25")))),
            ("Above Sunstones", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or ((state.has("tricks;SNMissiles;2") and state.has("items;missile;22")) or (state.has("tricks;SNMissiles;3") and state.has("items;missile;11")) or (state.has("tricks;SNMissiles;4") and state.has("items;missile;1")))),
            ("Refill (Upper)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Outside Jenka's House",
        [
            ("Door to Jenka's House", lambda state, player: True),
            ("Lower Side", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or ((state.has("tricks;SNMissiles;2") and state.has("items;missile;3")) or (state.has("tricks;SNMissiles;3") and state.has("items;missile;1")))),
            ("Above Sunstones", lambda state, player: ((state.has("tricks;SNMissiles;2") and state.has("items;missile;4")) or (state.has("tricks;SNMissiles;3") and state.has("items;missile;2")) or (state.has("tricks;SNMissiles;4") and state.has("items;missile;1")) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or can_break_blocks(state, player)) and state.has("events;eventOmega;1")),
            ("Pawprint Spot", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;2") and state.has("items;missiles;3")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Pawprint Spot",
        [
            ("Pickup (Pawprint Spot)", lambda state, player: True),
            ("Pickup (Puppy (Chest))", lambda state, player: True),
            ("Above Sunstones", lambda state, player: state.has("events;eventOmega;1") and (can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;2") and state.has("items;missiles;3")))),
            ("Outside Jenka's House", lambda state, player: can_break_blocks(state, player) or (state.has("tricks;SNBubbler;1") and state.has("items;bubbler;1")) or (state.has("tricks;SNMissiles;2") and state.has("items;missiles;3")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Refill (Upper)",
        [
            ("Before Omega", lambda state, player: True),
            ("Save Point (Upper)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Refill (Lower)",
        [
            ("Outside Sand Zone Storehouse", lambda state, player: True),
            ("Save Point (Lower)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Teleporter to Labyrinth I",
        [
            ("Outside Sand Zone Storehouse", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Outside Sand Zone Storehouse",
        [
            ("Lower Side", lambda state, player: has_weapon(state, player) or (state.has("tricks;pacifist;1") and has_flight(state, player)) or state.has("tricks;pacifist;2")),
            ("Pickup (Puppy (Sleep))", lambda state, player: True),
            ("Exit to Sand Zone Storehouse", lambda state, player: True),
            ("Refill (Lower)", lambda state, player: True),
            ("Teleporter to Labyrinth I", lambda state, player: state.has("events;eventSandMazeTeleport;1") and remove_points_of_no_return(state, player))
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Save Point (Lower)",
        [
            ("Refill (Lower)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone - Save Point (Upper)",
        [
            ("Refill (Upper)", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone Residence - Door to Sand Zone",
        [
            ("Pickup (Curly Boss)", lambda state, player: state.has("events;eventFightCurly;1") and (state.has("items;polarStar;1") or state.has("items;spur;1"))),
            ("Door to Small Room", lambda state, player: True),
            ("Before Curly", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone Residence - Door to Small Room",
        [
            ("Door to Sand Zone", lambda state, player: True),
            ("Before Curly", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone Residence - Before Curly",
        [
            ("Event - Curly", lambda state, player: can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;1") and state.has("items;supers;1") and state.has("items;missile;9")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Small Room - Door to Sand Zone Residence",
        [
            ("Pickup (Puppy (Curly))", lambda state, player: True),
            ("Pickup (Curly's Closet)", lambda state, player: True),
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Small Room - Refill",
        [
            ("Door to Sand Zone Residence", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Small Room - Save Point",
        [
            ("Refill", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Jenka's House - Door to Sand Zone",
        [
            ("Pickup (Jenka)", lambda state, player: True),
            ("Event - Returned Puppies", lambda state, player: True),
            ("Save Point", lambda state, player: True),
            ("Hint - Jenka 1", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Jenka's House - Save Point",
        [
            ("Door to Sand Zone", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Deserted House - Door to Sand Zone",
        [
            ("Pickup (Puppy (Dark))", lambda state, player: True),
            ("Save Point", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Deserted House - Save Point",
        [
            ("Door to Sand Zone", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone Storehouse - Entrance from Sand Zone",
        [
            ("Before Toroko+", lambda state, player: True),
            ("Exit to Labyrinth I", lambda state, player: True)
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone Storehouse - Before Toroko+",
        [
            ("Event - Toroko+", lambda state, player: can_kill_bosses(state, player) or (state.has("tricks;BossMissiles;2") and state.has("items;supers;1") and state.has("items;missile;13")) or (state.has("tricks;BossMissiles;4") and state.has("items;missiles;1") and state.has("items;missile;30")))
        ],
        [
            
        ]
    ),
    RegionData(
        "Sand Zone Storehouse - Exit to Labyrinth I",
        [
            
        ],
        [
            
        ]
    ),
]

